spring.application.name=gymmanagement

spring.datasource.url=jdbc:mysql://mysql-a0b85f6-sudalaimani733-e61d.h.aivencloud.com:27801/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=PASTE_YOUR_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=pulsegym_super_secret_key_for_jwt_2024
jwt.expiration=86400000